import { atom } from "jotai";

export const menuOpen = atom(false);
export const menuSelected = atom("home");
export const popUpOpen = atom(false);
export const activeViewMenu = atom(1);
export const activeSearchView = atom(false);
export const searchQuery = atom("");
export const isSearchOpen = atom(false);
export const OpOrScript = atom(true);
export const ColorOpCode = atom(true);
export const ColorScript = atom(false);
export const popUpExampleOpen = atom(false);
export const modularPopUp = atom(false);
export const isRawHex = atom(false);
export const isRawHexAndState = atom("3");
export const isTxId = atom(false);
export const isTxIdAndState = atom("3");
export const isVersion = atom("1");
export const isClickedModularPopUpOpen = atom(false);
export const TxTextSectionHoverScriptAtom = atom<number[]>([]);
export const TxTextSectionClickScript = atom<number[]>([]);
export const hoveredImageMember = atom("");
export const userSignedIn = atom(false);
export const resetPassword = atom(false);
export const resetEmail = atom(false);
export const hashingAlgorithm = atom("HASH256");
