export const EDCSA_STEPS = [
  {
    id: 1,
    name: "r",
    description: "Generate a random number r",
    input: "r",
    output: "r",
    next: 2,
    prev: null,
    type: "random",
  },
  {
    id: 2,
    name: "k^-1",
    description: "Calculate k^-1",
    input: "r",
    output: "k^-1",
    next: 3,
    prev: 1,
    type: "inverse",
  },
  {
    id: 3,
    name: "e",
    description: "Calculate e",
    input: "k^-1",
    output: "e",
    next: 4,
    prev: 2,
    type: "hash",
  },
  {
    id: 4,
    name: "h(m)",
    description: "Calculate h(m)",
    input: "e",
    output: "h(m)",
    next: 5,
    prev: 3,
    type: "hash",
  },
  {
    id: 5,
    name: "s",
    description: "Calculate s",
    input: "h(m)",
    output: "s",
    next: null,
    prev: 4,
    type: "multiply",
  },
];
